### ISSUE TITLE
Script for Getting Links from Database

### ISSUE THREAD

**Issue by jaredb1011** [waldo-vision/models#1]
### Description:
We need code that downloads sets of gameplay video URLs submitted by users of **waldo.vision** and stored in our SQL database. The code should ensure the URLs are valid, have been reviewed by users 25 or more times, and have a 90% or higher positive rating. The code must also prevent downloading duplicate links. The analysis team will need to coordinate with the infrastructure team to identify the best way to download these URLs.

### Requirements:
- Coordinate with the infrastructure team to establish the best method for accessing the SQL database.
- Query the SQL database to retrieve URLs of gameplay videos that meet the following criteria:
1.    Have been reviewed by users 25 or more times
2.    Have a 90% or higher positive rating
- Validate the retrieved URLs to ensure they are valid gameplay video URLs.
- Check for and avoid downloading duplicate links.
- Handle download errors, such as network issues or invalid URLs, gracefully.
- Provide clear documentation on how to use the code and specify the download directory and format.

### Acceptance Criteria:
- Successful coordination with the infrastructure team to establish the best method for accessing the SQL database.
- Successfully query the SQL database to retrieve URLs of gameplay videos that meet the specified criteria (reviewed 25+ times and 90%+ positive rating).
- Validate the retrieved URLs to ensure they are valid gameplay video URLs with at least 95% accuracy.
- Check for and avoid downloading duplicate links.
- Save downloaded links to a specified file.
- Handle download errors, such as network issues or invalid URLs, gracefully, without crashing the program.
- Clear documentation provided on how to use the code and specify the download file and format.

### Notes:
Consider using an ORM (Object-Relational Mapper) library, such as SQLAlchemy, to interact with the SQL database in a more pythonic and maintainable way.

**Comment by Joe-TheBro** [comment]
Ready for review #7

**Comment by mattolson93** [comment]
merged
